### ISSUE TITLE
[benchmarks] Split the Parsec 3.0 image in two parts

### ISSUE THREAD

**Issue by mcolmant** [Spirals-Team/benchmark-containers#12]
Currently, the docker image for Parsec benchmarks are minified and source are removed before the final commit. It is thus impossible to re-compile manually some benchmarks.

For this reason, it will be interesting to separate this image in two. The first image will allow to install all necessary packages, to download Parsec 3.0, to apply all patches, to create the missing links for inputs and to compress all available inputs.

The second image will be based on the first one and it will allow to build all benchmarks (builds cleaned + sources removed) and to launch easily a benchmark with the extended `run.sh` script.

**Comment by ouap** [comment]
Done
