### ISSUE TITLE
[parsec-3.0] netapps benchmarks

### ISSUE THREAD

**Issue by mcolmant** [Spirals-Team/benchmark-containers#4]
Benchmarks `parsec.netdedup`, `parsec.netferret`, `parsec.netstreamcluster` are not correctly built.
The same error is described and fixed [here](https://lists.cs.princeton.edu/pipermail/parsec-users/2012-November/001474.html).
You can consider fixing it automatically by applying a patch.

**Comment by ouap** [comment]
Netapps benchmarks compile in the last commit
