### ISSUE TITLE
[parsec-3.0] Compress the input workloads

### ISSUE THREAD

**Issue by rouvoy** [Spirals-Team/benchmark-containers#6]
You can save further disk space by compressing the input workloads that are shipped with PARSEC.

This requires the following updates:
1. After unzipping the PARSEC archive, execute the command `find . -name \*.tar -exec xz -9 \{\} \;` to compress all the input workloads (this should save about 4GB).
2. The command `run.sh` should be extended to include a `use` primitive that unzips a given workload whose value can only be `benchmark|all:test`|`native`|`simdev`|`simlarge`|`simmedium`|`simsmall`. If the workload is not unzipped _a priori_, the command `run.sh` will do it implicitly.

**Comment by mcolmant** [comment]
What is the status of this issue? @ouap

**Comment by ouap** [comment]
It's done, I think so at least. Do I need to make a new pull request ?

**Comment by mcolmant** [comment]
Yes, thank you 

Envoyé de mon iPhone
